### ISSUE TITLE
Verify Branded token economies can be created by staking ERC20 token with any decimal.

### ISSUE THREAD

**Issue by sarvesh-ost** [OpenST/JLP#96]
As an economy owner
I want to stake ERC20 coin like USDC with 6 decimals
 so that I can create branded token economies.

Theoretically, branded token and EIP20Gateway support stake and mint of any ERC20 token. 
This ticket is about proving this theory by performing stake and mint for stable currency USDC which has decimal 6. 

Contract : https://github.com/centrehq/centre-tokens/blob/master/contracts/FiatTokenV1.sol

https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48

Following unknowns should be answered with this ticket: 

1. Is the staking of ERC20 token(value token) with decimal other than 18 is possible? does it mint expected value? 
2. What is the relationship between value token decimal and branded token decimal? They must be the same or different? what are the implications of this? 
3. Is it possible to have different decimals in value token and branded token with the current implementation? (Given stake and mint should work as expected)?

**Comment by jasonklein** [comment]
@sarvesh-ost: can you clarify two points?
1️⃣ Does the _stability_ aspect of the stable coin matter or is it just that its decimals are not 18?
2️⃣ Is it that the _value token_ does not have 18 decimals or the _branded token_ does not have 18 decimals?

**Comment by sarvesh-ost** [comment]
> @sarvesh-ost: can you clarify two points?
> 1️⃣ Does the _stability_ aspect of the stable coin matter or is it just that its decimals are not 18?

I think not, in this context this token is simply an ERC20 token.
> 2️⃣ Is it that the _value token_ does not have 18 decimals or the _branded token_ does not have 18 decimals?

I think both tokens decimal can be different from 18.

**Comment by sarvesh-ost** [comment]
@jasonklein  @schemar  I have also added questions/unknowns that should be answered with this ticket in the ticket description.  Please have a look.

**Comment by schemar** [comment]
Thanks. From my understanding:

> 1. Is the staking of ERC20 token(value token) with decimal other than 18 is possible? does it mint expected value?

Should work "out of the box".

> 2. What is the relationship between valuetoken decimal and branded token decimal? They must be the same or different? what are the implications of this?

In my opinion they must be the same at the moment.

> 3. Is it possible to have different decimals in value token and branded token with the current implementation? (Given stake and mint should work as expected)?

I would argue *no.*

**Comment by jasonklein** [comment]
Thanks for the additions, @sarvesh-ost. Thoughts below:
> Is the staking of ERC20 token(value token) with decimal other than 18 is possible? does it mint expected value?

I second @schemar; neither the value token decimals nor the branded token decimals play any role in staking/minting. *But that is a separate question* from the "expected" value (and this is what is causing so much confusion).

> What is the relationship between valuetoken decimal and branded token decimal? They must be the same or different? what are the implications of this?

As the decimals are representational, I'd say that their relationship is conceptual. I would argue that we have left the handling of this representation to the presentation layer thus far, even if only implicitly. I do not see any reason to change that arrangement now and running staking a value token with different decimals from the branded token will not, itself, change that arrangement. If we want to change that arrangement, we need to first decide what we want to change about it.

So, here, I disagree with @schemar, to the extent that the protocol *does not need to come to a conclusion about this*. This relationship can and should be handled at the presentation layer.

> Is it possible to have different decimals in value token and branded token with the current implementation?(Given stake and mint should work as expected)?

Yes, because, again, the decimals play no role—our contracts never even query the value token for its decimal information (which is consistent with the [token guidance](https://eips.ethereum.org/EIPS/eip-20): "This method can be used to improve usability, but interfaces and other contracts MUST NOT expect these values to be present.").

I agree with @schemar re: user expectations. But I think, like the conceptual relationship between the two tokens, user expectations can be handled elsewhere.

**Comment by deepesh-kn** [comment]
This epic covers the tests related to arbitrary decimals.
https://github.com/OpenST/JLP/issues/98

This ticket now validates that the decimals of the staked token are equal to the decimals of BT. So this makes sure that the branded token economies can be created by staking ERC20 token with any decimals that implements `decimals()` function.
https://github.com/openst/brandedtoken-contracts/issues/171

closing this ticket.
